name: "Has Changed Path Bis"
description: "Detects whether a path or a combination of paths were changed in the previous commit"
inputs:
  paths: # one or more paths
    description: "Paths to detect changes"
    required: true
  lsc:
    description: "Last successful commit"
    required: false
outputs:
  changed:
    description: "Boolean indicating if the paths were changed in previous commit"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: terminal
  color: gray-dark
